export const CIPOK = [
    {
        tipus: ["osszes","magasszaru"],
        nev: "Magasszárú Kék Jordan 1",
        marka: "Jordan",
        meret: [42, 43, 44],
        szin: "Kék",
        ar: 69990,
        db: 3,
        kep: "./kepek/magasszaru1.png",
    },
    {
        tipus: ["osszes","magasszaru"],
        nev: "Magasszárú Barna Jordan 1",
        marka: "Jordan",
        meret: [40, 41, 42, 45],
        szin: "Barna",
        ar: 79990,
        db: 5,
        kep: "./kepek/magasszaru2.webp",
    },
    {
        tipus: ["osszes","magasszaru"],
        nev: "Magasszárú Sárga Jordan 1",
        marka: "Jordan",
        meret: [39, 42, 43, 44],
        szin: "Sárga",
        ar: 119990,
        db: 4,
        kep: "./kepek/magasszaru3.webp",
    },
    {
        tipus: ["osszes","alacsonyszaru"],
        nev: "Alacsonyszárú Sárga Jordan 1",
        marka: "Jordan",
        meret: [40,41,44,46],
        szin: "Sárga",
        ar: 44990,
        db: 4,
        kep: "./kepek/alacsonyszaru1.png",
    },
    {
        tipus: ["osszes","alacsonyszaru"],
        nev: "Alacsonyszárú Fekete Jordan 1",
        marka: "Jordan",
        meret: [38,41,42,44],
        szin: "Fekete",
        ar: 48990,
        db: 4,
        kep: "./kepek/alacsonyszaru3.webp",
    },
    {
        tipus: ["osszes","alacsonyszaru"],
        nev: "Alacsonyszárú Kék Jordan 1",
        marka: "Jordan",
        meret: [40,41,42,43,44],
        szin: "Kék",
        ar: 54990,
        db: 5,
        kep: "./kepek/alacsonyszaru2.webp",
    },
];